/*-----------------------------------------------LOGIN-----------------------------------------------*/
###Login
POST http://localhost:3000/v1/login
Content-Type: application/json

{
  "usuario": "admin1",
  "password": "admin"

}
/*-----------------------------------------------USUARIOS-----------------------------------------------*/
###Register (Create User)
POST http://localhost:3000/v1/register
Content-Type: application/json

{
  "usuario": "admin2",
  "password": "admin",
  "nombre": "admin2",
  "roleId": 1
  }
###Get All Users
GET http://localhost:3000/v1/users

###Get User by Id
GET http://localhost:3000/v1/users/8

###Update User
PATCH http://localhost:3000/v1/users/2
Content-Type: application/json

{
  "usuario": "adminUpdate2",
  "password": "admin",
  "nombre": "adminUpdate2",
  "roleId": 1
  }
###Delete User
DELETE http://localhost:3000/v1/users/2
/*-----------------------------------------------CATEGORIAS-----------------------------------------------*/
###Create categoria
POST http://localhost:3000/v1/categoria
Content-Type: application/json

{
  "nombre_categoria": "categoria2",
  "descripcion": "descripcion2"
  }
###Get All Categorias
GET http://localhost:3000/v1/categorias
###Get Categoria by Id
GET http://localhost:3000/v1/categorias/8
###Update Categoria
PATCH http://localhost:3000/v1/categorias/1
Content-Type: application/json

{
  "nombre_categoria": "categoriaUpdate1",
  "descripcion": "descripcionUpdate1"
  }
###Delete Categoria
DELETE http://localhost:3000/v1/categorias/1

/*-----------------------------------------------PROVEEDORES-----------------------------------------------*/
###Create Proveedor
POST http://localhost:3000/v1/proveedor
Content-Type: application/json

{
  "nombre_proveedor": "proveedor3",
  "telefono": "telefono3",
  "direccion": "direccion3",
  "email": "email3"
  }
###Get All Proveedores
GET http://localhost:3000/v1/proveedores
###Get Proveedor by Id
GET http://localhost:3000/v1/proveedores/1
###Update Proveedor
PATCH http://localhost:3000/v1/proveedores/55
Content-Type: application/json

{
  "nombre_proveedor": "proveedorUpdate55",
  "telefono": "telefonoUpdate1",
  "direccion": "direccionUpdate1",
  "email": "emailUpdate1"
  }
###Delete Proveedor
DELETE http://localhost:3000/v1/proveedores/1
/*-----------------------------------------------PRODUCTOS-----------------------------------------------*/
###Create Producto
POST http://localhost:3000/v1/producto
Content-Type: application/json

{
  "nombre_producto": "producto1",
  "descripcion": "descripcion1",
  "precio": 100,
  "cantidad": 10,
  "idCategoria": 2,
  "idProveedor": 2
  }
###Get All Productos
GET http://localhost:3000/v1/productos
###Get Producto by Id
GET http://localhost:3000/v1/productos/6
###Update Producto
PATCH http://localhost:3000/v1/productos/5
Content-Type: application/json

{
  "nombre_producto": "productoUpdate1",
  "descripcion": "descripcionUpdate1",
  "precio": 100,
  "cantidad": 10,
  "idCategoria": 2,
  "idProveedor": 2
  }
###Delete Producto
DELETE http://localhost:3000/v1/productos/5
/*-----------------------------------------------MOVIMIENTOS-----------------------------------------------*/
###Create Movimiento para registrar entrada el tipo de movimiento tiene que decir "entrada" y para registrar salida el tipo de movimiento tiene que decir "salida"  
POST http://localhost:3000/v1/movimientos
Content-Type: application/json

{
  "id_producto": 7,
  "tipo_movimiento": "entrada",
  "cantidad": 10,
  "id_usuario": 1
  }
### Obtener todos los movimientos
GET http://localhost:3000/v1/movimientos
### Movimientos de un producto específico
GET http://localhost:3000/v1/movimientos?id_producto=6
### Movimientos realizados por un usuario específico
GET http://localhost:3000/v1/movimientos?id_usuario=1
### Movimientos de tipo "entrada"
GET http://localhost:3000/v1/movimientos?tipo_movimiento=entrada
### Movimientos de tipo "salida"
GET http://localhost:3000/v1/movimientos?tipo_movimiento=salida
### Movimientos en un rango de fechas
GET http://localhost:3000/v1/movimientos?fecha_inicio=2024-01-01&fecha_fin=2025-01-01
### Movimientos con paginación (primeros 10 movimientos)
GET http://localhost:3000/v1/movimientos?limit=10&offset=0
### Movimientos con paginación (siguientes 10 movimientos)
GET http://localhost:3000/v1/movimientos?limit=10&offset=10
